export default function AboutPage() {
  return (
    <main>
      <header className="site-header"><a className="brand" href="/"><span className="brand-mark">SB</span><span>Sugar Bytes</span></a><nav className="nav"><a href="/learn">Learn</a><a href="/lab">Lab</a><a href="/dev-voices">Dev Voices</a><a href="/dx-check">DX Check</a><a href="/speaking">Speaking</a></nav><a className="button button-small" href="/about">About</a></header>
      <section className="section about-section"><div><p className="kicker">ABOUT SUGAR BYTES</p><h1>Built for developers. Informed by developers.</h1></div><div><p>Sugar Bytes is an independent developer education and advocacy platform focused on making technical ideas clearer, more useful, and easier to put into practice.</p><p>Through tutorials, experiments, developer conversations, community insight, and hands-on DX analysis, Sugar Bytes examines how software gets built, where developers encounter friction, and what better developer experiences can look like.</p><p>The platform is designed to grow alongside the community it serves: publishing what is useful, testing what is unclear, and turning real developer experience into better questions, better resources, and better tools.</p></div></section>
      <section className="section muted-section"><div className="section-heading"><p className="kicker">THE MODEL</p><h2>Teach. Build. Listen. Advocate.</h2><p>Technical education starts the conversation. Experiments create evidence. Developer voices reveal patterns. Advocacy turns those patterns into useful insight for both developers and product teams.</p></div><div className="program-grid"><article className="program-card"><p className="kicker">TEACH</p><h3>Make difficult ideas usable.</h3></article><article className="program-card"><p className="kicker">BUILD</p><h3>Prove it with runnable examples.</h3></article><article className="program-card"><p className="kicker">LISTEN</p><h3>Center real developer experience.</h3></article></div></section>
      <footer><div className="brand"><span className="brand-mark">SB</span><span>Sugar Bytes</span></div><p>Build better. Understand deeper.</p><p>© 2026 Sugar Bytes</p></footer>
    </main>
  );
}
